services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: "unless-stopped"
    volumes:
      - ./logs:/logs
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: "unless-stopped"
